config/routes.rb
Rails.application.routes.draw do
  get 'articles' => 'articles#index'
  # get 'posts/new'
  post '/articles' => 'articles#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

get '/' => 'homes#top'
get '/article/new' => 'articles#new'

get '/articles/:id' => 'articles#show', as: 'article'

get '/top' => 'articles#new'

get 'articles' => 'articles#new'

get '/articles/:id/edit' => 'articles#edit', as: 'edit_article'

patch '/articles/:id' => 'articles#update', as: 'update_article'

delete '/articles/:id' => 'articles#destroy', as: 'destroy_article'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
  	@article = Article.new
  end

  def create
  	  article = Article.new(article_params)

  	  article.save

  	  redirect_to articles_path
  end

  def index
    @articles = Article.all
    @article = Article.new

    end

  def edit
       @article = Article.find(params[:id])
  end

  def update
         article = Article.find(params[:id])
            article.update(article_params)
            redirect_to article_path(article.id)
  end
  
  def destroy
       article = Article.find(params[:id])
        article.destroy
        redirect_to articles_path
  end

  def show
      @article = Article.find(params[:id])
    end

  private

  def article_params
  	params.require(:article).permit(:title, :body, :weather, :time)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  	@article = Article.new
  end

  def create
  	  post = Article.new(post_params)
  	  article.save
  	  redirect_to articles_new_path
  end

  private
  def post_params
  	params.require(:article).permit(:title, :body, :author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/articles/edit.html.erb
<h1>編集画面</h1>
<%= form_for(@article) do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>
    <h4>本文</h4>
    <%= f.text_area :body %>
    <%= f.submit '保存' %>
<% end %>

app/views/articles/index.html.erb
<div class="container-fluid">
  <div class="row">

    <ul class="nav nav-tabs">
          <li role="presentation" class="active"><a href="#">takesimadialy</a></li>
          <li role="presentation"><a href="#">メニューＡ</a></li>
          <li role="presentation"><a href="#">メニューＢ</a></li>
          <li role="presentation"><a href="#">メニューC</a></li>
    </ul>

      <div class="col-md-4">

          <h1>新規投稿</h1>
          <%= form_for(@article) do |f| %>

          <h4>タイトル</h4>
          <%= f.text_field :title %>

          <h4>天気</h4>
          <%= f.text_field :weather %>

          <h4>本文</h4>
          <%= f.text_area :body %>

          <h4>投稿した時間</h4>
          <%= f.text_area :time %>

          <%= f.submit '投稿' %>

           <% end %>

       </div>


      <div class="col-md-8">

          <h1>投稿一覧</h1>
        
        <table width="100%">

            <tr>
                      <th>タイトル</th>

                      <th>天気</th>

                      <th>本文</th>

                      <th>投稿した時間</th>
               
            </tr>

            <% @articles.each do |article| %>

                  <tr>
                   <td>
                    <p>
                    	<%=link_to article.title, "/articles/#{article.id}" %>
                    </p>
                   </td>

                   <td>
                    <p>
                    	<%= article.weather %>
                    </p>
                   </td>


                   <td>
                    <p>
                    	<%=link_to article.body, "/articles/#{article.id}" %>
                    </p>
                   </td>

                   <td>
                    <p>
                    	<%=link_to article.time, "/articles/#{article.id}" %>
                    </p>
                   </td>
                  </tr>

              <% end %>
         </table>

      </div>
  </div>
</div>



app/views/articles/new.html.erb
<h1>新規投稿</h1>
<%= form_for(@article) do |f| %>

<h4>タイトル</h4>
<%= f.text_field :title %>

<h4>天気</h4>
<%= f.text_field :weather %>

<h4>本文</h4>
<%= f.text_area :body %>

<h4>投稿した時間</h4>
<%= f.text_area :time %>

<%= f.submit '投稿' %>

<% end %>

app/views/articles/show.html.erb
<h2>タイトル</h2>
<p><%= @article.title %></p>
<h2>本文</h2>
<p><%= @article.body %></p>
<h2>天気</h2>
<p><%= @article.weather %></p>
<h2>投稿時間</h2>
<p><%= @article.time %></p>

<%= link_to "編集", edit_article_path(@article.id) %>
<%= link_to "一覧ページに戻す", articles_path %>

<%= link_to "削除", destroy_article_path(@article.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>

app/views/homes/top.html.erb
<h1>　竹島勇一 </h1>
<%= image_tag'inu.jpg'%>
<h2>　産業能率大学 </h2>

<h3><%= link_to '新規投稿はこちら！', '/article/new' %><h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Takeshimadialy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
 <% @articles.each do |article| %>
    <p>タイトル</p>
    <span>
    	<%= article.title %>
    </span>
 <% end %>

app/views/posts/new.html.erb
<h1>Articles#new</h1>

<%= form_for(@article) do |f|%>
<h4>title</h4>
<%= f.text_field :title %>
<h4>著者</h4>
<%= f.text_area :author %>
<h4>本文</h4>
<%= f.text_area :body %>
<%= f.submit '投稿' %>
<% end %>